version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  features:
    build:
      context: ./features
    depends_on:
      - rabbitmq

  metric:
    build:
      context: ./metric
    depends_on:
      - rabbitmq
    volumes:
      - ./logs:/app/logs

  plot:
    build:
      context: ./plot
    depends_on:
      - rabbitmq
    volumes:
      - ./logs:/app/logs
